version: 0.3.14-{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
clone_folder: c:\gopath\src\github.com\KouKouChan\CSO2-Server
environment:
  GOPATH: c:\gopath
build_script:
- cmd: >-
    path=%path%;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

    gcc --version

    go version

    go build
test_script:
- cmd: >-
    move .\CSO2-Server.exe ..\

    move .\local-console.bat ..\

    cd ..

    7z a .\CSO2-Server-0.3.14-Win64.7z .\CSO2-Server.exe

    7z a .\CSO2-Server-0.3.14-Win64.7z .\local-console.bat

    7z a .\CSO2-Server-0.3.14-Win64.7z CSO2-Server\configure\server.conf

    7z a .\CSO2-Server-0.3.14-Win64.7z CSO2-Server\database\sqlite\cso2.db

    7z a .\CSO2-Server-0.3.14-Win64.7z CSO2-Server\assert\bg.jpg

    7z a .\CSO2-Server-0.3.14-Win64.7z CSO2-Server\assert\register.html

    7z a .\CSO2-Server-0.3.14-Win64.7z CSO2-Server\assert\cstrike\

    7z a .\CSO2-Server-0.3.14-Win64.7z CSO2-Server\locales\

    mv .\CSO2-Server-0.3.14-Win64.7z .\CSO2-Server\

    cd .\CSO2-Server\
artifacts:
- path: CSO2-Server-*-Win64.7z
  name: win64